# Generated by Django 4.2.2 on 2023-06-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_note_file_note_note_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noteshare',
            name='note',
        ),
        migrations.AddField(
            model_name='noteshare',
            name='note',
            field=models.ManyToManyField(related_name='shares', to='master.note'),
        ),
    ]
